/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#004ac6",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-high": "#dce9ff",
        "status-warning": "#f59e0b",
        secondary: "#0058be",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-dim": "#cbdbf5",
        "surface-muted": "#f8fafc",
        "outline-variant": "#c3c6d7",
        "accent-vivid": "#6161ff",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "status-error": "#ef4444",
        "on-error-container": "#93000a",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#0053db",
        "border-subtle": "#e2e8f0",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "tertiary-container": "#bc4800",
        "secondary-container": "#2170e4",
        "surface-base": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "status-success": "#10b981",
        "on-background": "#0b1c30",
        "on-secondary-fixed-variant": "#004395",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-primary-container": "#eeefff",
        "surface-bright": "#f8f9ff",
        tertiary: "#943700",
        "on-tertiary-container": "#ffede6",
        "primary-container": "#2563eb",
        "on-surface-variant": "#434655",
        "secondary-fixed": "#d8e2ff",
        background: "#f8f9ff",
        outline: "#737686",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary-container": "#fefcff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed": "#360f00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-desktop": "32px",
        "margin-md": "24px",
        gutter: "24px",
        "margin-sm": "12px",
        base: "8px",
        "container-padding-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
